// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var countryCodesArray = /* array */[
  "93",
  "355"
];

function optionCountryCode(codeOption) {
  if (codeOption !== undefined) {
    var code = codeOption;
    switch (code) {
      case "213" : 
      case "355" : 
      case "93" : 
          return code;
      default:
        return undefined;
    }
  }
  
}

var CountryCodes = /* module */[
  /* countryCodesArray */countryCodesArray,
  /* optionCountryCode */optionCountryCode
];

exports.CountryCodes = CountryCodes;
/* No side effect */
