// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function appendString1(a, b) {
  return a + b;
}

function appendString2(a, b, c) {
  return a + (b + c);
}

function appendString3(a, b, c, d) {
  return a + (b + (c + d));
}

function appendString4(a, b, c, d, e) {
  return a + (b + (c + (d + e)));
}

function appendString5(a, b, c, d, e, f) {
  return a + (b + (c + (d + (e + f))));
}

function appendString6(a, b, c, d, e, f, g) {
  return a + (b + (c + (d + (e + (f + g)))));
}

function appendString7(a, b, c, d, e, f, g, h) {
  return a + (b + (c + (d + (e + (f + (g + h))))));
}

function appendString8(a, b, c, d, e, f, g, h, i) {
  return a + (b + (c + (d + (e + (f + (g + (h + i)))))));
}

function appendString9(a, b, c, d, e, f, g, h, i, j) {
  return a + (b + (c + (d + (e + (f + (g + (h + (i + j))))))));
}

function appendString10(a, b, c, d, e, f, g, h, i, j, k) {
  return a + (b + (c + (d + (e + (f + (g + (h + (i + (j + k)))))))));
}

var unsafeArrayJoin = ( (sep, arr) => arr.join(sep) );

function appendChar1(a, b) {
  return a + $$String.make(1, b);
}

function appendChar2(a, b, c) {
  return a + ($$String.make(1, b) + $$String.make(1, c));
}

function appendChar3(a, b, c, d) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + $$String.make(1, d)));
}

function appendChar4(a, b, c, d, e) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + $$String.make(1, e))));
}

function appendChar5(a, b, c, d, e, f) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + ($$String.make(1, e) + $$String.make(1, f)))));
}

function appendChar6(a, b, c, d, e, f, g) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + ($$String.make(1, e) + ($$String.make(1, f) + $$String.make(1, g))))));
}

function appendChar7(a, b, c, d, e, f, g, h) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + ($$String.make(1, e) + ($$String.make(1, f) + ($$String.make(1, g) + $$String.make(1, h)))))));
}

function appendChar8(a, b, c, d, e, f, g, h, i) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + ($$String.make(1, e) + ($$String.make(1, f) + ($$String.make(1, g) + ($$String.make(1, h) + $$String.make(1, i))))))));
}

function appendChar9(a, b, c, d, e, f, g, h, i, j) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + ($$String.make(1, e) + ($$String.make(1, f) + ($$String.make(1, g) + ($$String.make(1, h) + ($$String.make(1, i) + $$String.make(1, j)))))))));
}

function appendChar10(a, b, c, d, e, f, g, h, i, j, k) {
  return a + ($$String.make(1, b) + ($$String.make(1, c) + ($$String.make(1, d) + ($$String.make(1, e) + ($$String.make(1, f) + ($$String.make(1, g) + ($$String.make(1, h) + ($$String.make(1, i) + ($$String.make(1, j) + $$String.make(1, k))))))))));
}

exports.appendString1 = appendString1;
exports.appendString2 = appendString2;
exports.appendString3 = appendString3;
exports.appendString4 = appendString4;
exports.appendString5 = appendString5;
exports.appendString6 = appendString6;
exports.appendString7 = appendString7;
exports.appendString8 = appendString8;
exports.appendString9 = appendString9;
exports.appendString10 = appendString10;
exports.unsafeArrayJoin = unsafeArrayJoin;
exports.appendChar1 = appendChar1;
exports.appendChar2 = appendChar2;
exports.appendChar3 = appendChar3;
exports.appendChar4 = appendChar4;
exports.appendChar5 = appendChar5;
exports.appendChar6 = appendChar6;
exports.appendChar7 = appendChar7;
exports.appendChar8 = appendChar8;
exports.appendChar9 = appendChar9;
exports.appendChar10 = appendChar10;
/* unsafeArrayJoin Not a pure module */
