// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function Simple_(T) {
  return /* module */[];
}

function WithProps_(T) {
  return /* module */[];
}

var T = /* module */[];

var Impl = /* module */[
  /* Simple_ */Simple_,
  /* WithProps_ */WithProps_,
  /* T */T
];

var T$1 = 0;

exports.Impl = Impl;
exports.T = T$1;
/* No side effect */
