// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function nonZeroInt(n) {
  if (n !== 0) {
    return n;
  }
  
}

function addInt(a, b) {
  return a + b | 0;
}

function subtractInt(a, b) {
  return a - b | 0;
}

var multiplyInt = Caml_int32.imul;

function divideInt(a, b) {
  if (a !== 0 && b !== 0) {
    return Caml_int32.div(a, b);
  }
  
}

function addFloat(a, b) {
  return a + b;
}

function subtractFloat(a, b) {
  return a - b;
}

function multiplyFloat(a, b) {
  return a * b;
}

function divideFloat(a, b) {
  if (a !== 0 && b !== 0) {
    return a / b;
  }
  
}

exports.nonZeroInt = nonZeroInt;
exports.addInt = addInt;
exports.subtractInt = subtractInt;
exports.multiplyInt = multiplyInt;
exports.divideInt = divideInt;
exports.addFloat = addFloat;
exports.subtractFloat = subtractFloat;
exports.multiplyFloat = multiplyFloat;
exports.divideFloat = divideFloat;
/* No side effect */
