// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var Impl = /* module */[
  /* Virtual_Node */0,
  /* Child_List */0,
  /* Dom_Effect */0,
  /* Html_Tag */0,
  /* Attribute */0,
  /* Attribute_List */0,
  /* Virtual_Event */0
];

var Virtual_Node = 0;

var Child_List = 0;

var Dom_Effect = 0;

var Html_Tag = 0;

var Attribute = 0;

var Attribute_List = 0;

var Virtual_Event = 0;

exports.Impl = Impl;
exports.Virtual_Node = Virtual_Node;
exports.Child_List = Child_List;
exports.Dom_Effect = Dom_Effect;
exports.Html_Tag = Html_Tag;
exports.Attribute = Attribute;
exports.Attribute_List = Attribute_List;
exports.Virtual_Event = Virtual_Event;
/* No side effect */
