// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function validateCountryCode(codeOption) {
  if (codeOption !== undefined) {
    var code = codeOption;
    switch (code) {
      case "213" : 
      case "355" : 
      case "93" : 
          return code;
      default:
        return undefined;
    }
  }
  
}

var CountryCodes = /* module */[/* validateCountryCode */validateCountryCode];

exports.CountryCodes = CountryCodes;
/* No side effect */
