// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var Impl = /* module */[
  /* T : () */0,
  /* Virtual_Node_Type_Init : () */0,
  /* Child_List_Type_Init : () */0,
  /* Component_Type_Init : () */0,
  /* Abstract_Node_Type_Init : () */0
];

var T = /* () */0;

var Virtual_Node_Type_Init = /* () */0;

var Child_List_Type_Init = /* () */0;

var Component_Type_Init = /* () */0;

var Abstract_Node_Type_Init = /* () */0;

exports.Impl = Impl;
exports.T = T;
exports.Virtual_Node_Type_Init = Virtual_Node_Type_Init;
exports.Child_List_Type_Init = Child_List_Type_Init;
exports.Component_Type_Init = Component_Type_Init;
exports.Abstract_Node_Type_Init = Abstract_Node_Type_Init;
/* No side effect */
