// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function _lift1(v, z) {
  return Curry._1(z, v);
}

function _lift2(v, z) {
  return Curry._1(z, (function (param) {
                return Curry._1(param, v);
              }));
}

function _lift3(v, z) {
  return Curry._1(z, (function (param) {
                return Curry._1(param, (function (param) {
                              return _lift1(v, param);
                            }));
              }));
}

function _lift4(v, z) {
  return Curry._1(z, (function (param) {
                return Curry._1(param, (function (param) {
                              return _lift2(v, param);
                            }));
              }));
}

function _lift5(v, z) {
  return Curry._1(z, (function (param) {
                return Curry._1(param, (function (param) {
                              return _lift3(v, param);
                            }));
              }));
}

function _lift6(v, z) {
  return Curry._1(z, (function (param) {
                return Curry._1(param, (function (param) {
                              return _lift4(v, param);
                            }));
              }));
}

function _lift7(v, z) {
  return Curry._1(z, (function (param) {
                return Curry._1(param, (function (param) {
                              return _lift5(v, param);
                            }));
              }));
}

function lift1(v, a) {
  return Curry._1(a, v);
}

function lift2(v, a, b) {
  return /* tuple */[
          Curry._1(a, v),
          Curry._1(b, v)
        ];
}

function lift3(v, a, b, c) {
  return /* tuple */[
          Curry._1(a, v),
          Curry._1(b, v),
          Curry._1(c, v)
        ];
}

function lift4(v, a, b, c, d) {
  return /* tuple */[
          Curry._1(a, v),
          Curry._1(b, v),
          Curry._1(c, v),
          Curry._1(d, v)
        ];
}

function lift5(v, a, b, c, d, e) {
  return /* tuple */[
          Curry._1(a, v),
          Curry._1(b, v),
          Curry._1(c, v),
          Curry._1(d, v),
          Curry._1(e, v)
        ];
}

function lift6(v, a, b, c, d, e, f) {
  return /* tuple */[
          Curry._1(a, v),
          Curry._1(b, v),
          Curry._1(c, v),
          Curry._1(d, v),
          Curry._1(e, v),
          Curry._1(f, v)
        ];
}

function apply1(v, a) {
  return Curry._1(v, a);
}

function apply2(v, a, b) {
  return /* tuple */[
          Curry._1(v, a),
          Curry._1(v, b)
        ];
}

function apply3(v, a, b, c) {
  return /* tuple */[
          Curry._1(v, a),
          Curry._1(v, b),
          Curry._1(v, c)
        ];
}

function apply4(v, a, b, c, d) {
  return /* tuple */[
          Curry._1(v, a),
          Curry._1(v, b),
          Curry._1(v, c),
          Curry._1(v, d)
        ];
}

function apply5(v, a, b, c, d, e) {
  return /* tuple */[
          Curry._1(v, a),
          Curry._1(v, b),
          Curry._1(v, c),
          Curry._1(v, d),
          Curry._1(v, e)
        ];
}

function apply6(v, a, b, c, d, e, f) {
  return /* tuple */[
          Curry._1(v, a),
          Curry._1(v, b),
          Curry._1(v, c),
          Curry._1(v, d),
          Curry._1(v, e),
          Curry._1(v, f)
        ];
}

function left(a, b) {
  return a;
}

function right(a, b) {
  return b;
}

function b1(a, b, c, d) {
  return Curry._1(a, Curry._2(b, c, d));
}

function flip(a, b, b$1) {
  return a;
}

exports._lift1 = _lift1;
exports._lift2 = _lift2;
exports._lift3 = _lift3;
exports._lift4 = _lift4;
exports._lift5 = _lift5;
exports._lift6 = _lift6;
exports._lift7 = _lift7;
exports.lift1 = lift1;
exports.lift2 = lift2;
exports.lift3 = lift3;
exports.lift4 = lift4;
exports.lift5 = lift5;
exports.lift6 = lift6;
exports.apply1 = apply1;
exports.apply2 = apply2;
exports.apply3 = apply3;
exports.apply4 = apply4;
exports.apply5 = apply5;
exports.apply6 = apply6;
exports.left = left;
exports.right = right;
exports.b1 = b1;
exports.flip = flip;
/* No side effect */
