// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function make(n) {
  return n;
}

function toString(n) {
  var str = "" + n[/* first */0];
  var match = n[/* second */1];
  var str$1 = match !== undefined ? match + str : str;
  var match$1 = n[/* third */2];
  var str$2 = match$1 !== undefined ? match$1 + str$1 : str$1;
  var match$2 = n[/* fourth */3];
  var str$3 = match$2 !== undefined ? match$2 + str$2 : str$2;
  return n[/* last */4] + str$3;
}

var FullName = /* module */[
  /* make */make,
  /* toString */toString
];

exports.FullName = FullName;
/* No side effect */
