// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var VirtualNode = 0;

var Component = 0;

var Props = 0;

exports.VirtualNode = VirtualNode;
exports.Component = Component;
exports.Props = Props;
/* No side effect */
