// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function Impl(T) {
  var Make = function (T) {
    return /* module */[];
  };
  return /* module */[/* Make */Make];
}

exports.Impl = Impl;
/* No side effect */
