// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function Make(T) {
  var update = T[/* update */0];
  return /* module */[/* update */update];
}

exports.Make = Make;
/* No side effect */
