// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function flatten(x) {
  if (x !== undefined) {
    var match = Caml_option.valFromOption(x);
    if (match !== undefined) {
      return Caml_option.some(Caml_option.valFromOption(match));
    } else {
      return undefined;
    }
  }
  
}

function map(fn, x) {
  if (x !== undefined) {
    return Caml_option.some(Curry._1(fn, Caml_option.valFromOption(x)));
  }
  
}

function flatMap(fn, x) {
  return flatten(map(fn, x));
}

exports.flatten = flatten;
exports.map = map;
exports.flatMap = flatMap;
/* No side effect */
