// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Webapi__Dom__Document = require("bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Document.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function map(f, param) {
  if (param !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(param)));
  }
  
}

function andThen(f, param) {
  if (param !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(param));
  }
  
}

function unwrapUnsafely(param) {
  if (param !== undefined) {
    return Caml_option.valFromOption(param);
  } else {
    throw [
          Caml_builtin_exceptions.invalid_argument,
          "Passed `None` to unwrapUnsafely"
        ];
  }
}

console.log("Hello, BuckleScript and Reason!");

var documentBody = andThen((function (prim) {
        return Caml_option.nullable_to_opt(prim.body);
      }), Webapi__Dom__Document.asHtmlDocument(document));

console.log(documentBody);

var appRoot = document.createElement("div").parentElement;

var header = document.createElement("h1");

var appRoot$1 = (appRoot == null) ? undefined : Caml_option.some(appRoot);

exports.map = map;
exports.andThen = andThen;
exports.unwrapUnsafely = unwrapUnsafely;
exports.documentBody = documentBody;
exports.appRoot = appRoot$1;
exports.header = header;
/*  Not a pure module */
