// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var CountryCodes_000 = /* afghanistan : record */[
  /* name */"Afghanistan",
  /* a2 */"AF",
  /* a3 */"AFG",
  /* num */"4",
  /* dial */"93"
];

var CountryCodes_001 = /* albania : record */[
  /* name */"Albania",
  /* a2 */"AL",
  /* a3 */"ALB",
  /* num */"8",
  /* dial */"355"
];

var CountryCodes_002 = /* algeria : record */[
  /* name */"Algeria",
  /* a2 */"DZ",
  /* a3 */"DZA",
  /* num */"12",
  /* dial */"213"
];

var CountryCodes_003 = /* americanSamoa : record */[
  /* name */"American Samoa",
  /* a2 */"AS",
  /* a3 */"ASM",
  /* num */"16",
  /* dial */"1-684"
];

var CountryCodes_004 = /* andorra : record */[
  /* name */"Andorra",
  /* a2 */"AD",
  /* a3 */"AND",
  /* num */"20",
  /* dial */"376"
];

var CountryCodes_005 = /* angola : record */[
  /* name */"Angola",
  /* a2 */"AO",
  /* a3 */"AGO",
  /* num */"24",
  /* dial */"244"
];

var CountryCodes_006 = /* anguilla : record */[
  /* name */"Anguilla",
  /* a2 */"AI",
  /* a3 */"AIA",
  /* num */"660",
  /* dial */"1-264"
];

var CountryCodes_007 = /* antarctica : record */[
  /* name */"Antarctica",
  /* a2 */"AQ",
  /* a3 */"ATA",
  /* num */"10",
  /* dial */"672"
];

var CountryCodes_008 = /* antiguaAndBarbuda : record */[
  /* name */"Antigua and Barbuda",
  /* a2 */"AG",
  /* a3 */"ATG",
  /* num */"28",
  /* dial */"1-268"
];

var CountryCodes_009 = /* argentina : record */[
  /* name */"Argentina",
  /* a2 */"AR",
  /* a3 */"ARG",
  /* num */"32",
  /* dial */"54"
];

var CountryCodes_010 = /* armenia : record */[
  /* name */"Armenia",
  /* a2 */"AM",
  /* a3 */"ARM",
  /* num */"51",
  /* dial */"374"
];

var CountryCodes_011 = /* aruba : record */[
  /* name */"Aruba",
  /* a2 */"AW",
  /* a3 */"ABW",
  /* num */"533",
  /* dial */"297"
];

var CountryCodes_012 = /* australia : record */[
  /* name */"Australia",
  /* a2 */"AU",
  /* a3 */"AUS",
  /* num */"36",
  /* dial */"61"
];

var CountryCodes_013 = /* austria : record */[
  /* name */"Austria",
  /* a2 */"AT",
  /* a3 */"AUT",
  /* num */"40",
  /* dial */"43"
];

var CountryCodes_014 = /* azerbaijan : record */[
  /* name */"Azerbaijan",
  /* a2 */"AZ",
  /* a3 */"AZE",
  /* num */"31",
  /* dial */"994"
];

var CountryCodes_015 = /* bahamas : record */[
  /* name */"Bahamas",
  /* a2 */"BS",
  /* a3 */"BHS",
  /* num */"44",
  /* dial */"1-242"
];

var CountryCodes_016 = /* bahrain : record */[
  /* name */"Bahrain",
  /* a2 */"BH",
  /* a3 */"BHR",
  /* num */"48",
  /* dial */"973"
];

var CountryCodes_017 = /* bangladesh : record */[
  /* name */"Bangladesh",
  /* a2 */"BD",
  /* a3 */"BGD",
  /* num */"50",
  /* dial */"880"
];

var CountryCodes_018 = /* barbados : record */[
  /* name */"Barbados",
  /* a2 */"BB",
  /* a3 */"BRB",
  /* num */"52",
  /* dial */"1-246"
];

var CountryCodes_019 = /* belarus : record */[
  /* name */"Belarus",
  /* a2 */"BY",
  /* a3 */"BLR",
  /* num */"112",
  /* dial */"375"
];

var CountryCodes_020 = /* belgium : record */[
  /* name */"Belgium",
  /* a2 */"BE",
  /* a3 */"BEL",
  /* num */"56",
  /* dial */"32"
];

var CountryCodes_021 = /* belize : record */[
  /* name */"Belize",
  /* a2 */"BZ",
  /* a3 */"BLZ",
  /* num */"84",
  /* dial */"501"
];

var CountryCodes_022 = /* benin : record */[
  /* name */"Benin",
  /* a2 */"BJ",
  /* a3 */"BEN",
  /* num */"204",
  /* dial */"229"
];

var CountryCodes_023 = /* bermuda : record */[
  /* name */"Bermuda",
  /* a2 */"BM",
  /* a3 */"BMU",
  /* num */"60",
  /* dial */"1-441"
];

var CountryCodes_024 = /* bhutan : record */[
  /* name */"Bhutan",
  /* a2 */"BT",
  /* a3 */"BTN",
  /* num */"64",
  /* dial */"975"
];

var CountryCodes_025 = /* bolivia : record */[
  /* name */"Bolivia",
  /* a2 */"BO",
  /* a3 */"BOL",
  /* num */"68",
  /* dial */"591"
];

var CountryCodes_026 = /* bonaire : record */[
  /* name */"Bonaire",
  /* a2 */"BQ",
  /* a3 */"BES",
  /* num */"535",
  /* dial */"599"
];

var CountryCodes_027 = /* bosniaAndHerzegovina : record */[
  /* name */"Bosnia and Herzegovina",
  /* a2 */"BA",
  /* a3 */"BIH",
  /* num */"70",
  /* dial */"387"
];

var CountryCodes_028 = /* botswana : record */[
  /* name */"Botswana",
  /* a2 */"BW",
  /* a3 */"BWA",
  /* num */"72",
  /* dial */"267"
];

var CountryCodes_029 = /* bouvetIsland : record */[
  /* name */"Bouvet Island",
  /* a2 */"BV",
  /* a3 */"BVT",
  /* num */"74",
  /* dial */"47"
];

var CountryCodes_030 = /* brazil : record */[
  /* name */"Brazil",
  /* a2 */"BR",
  /* a3 */"BRA",
  /* num */"76",
  /* dial */"55"
];

var CountryCodes_031 = /* britishIndianOceanTerritory : record */[
  /* name */"British Indian Ocean Territory",
  /* a2 */"IO",
  /* a3 */"IOT",
  /* num */"86",
  /* dial */"246"
];

var CountryCodes_032 = /* bruneiDarussalam : record */[
  /* name */"Brunei Darussalam",
  /* a2 */"BN",
  /* a3 */"BRN",
  /* num */"96",
  /* dial */"673"
];

var CountryCodes_033 = /* bulgaria : record */[
  /* name */"Bulgaria",
  /* a2 */"BG",
  /* a3 */"BGR",
  /* num */"100",
  /* dial */"359"
];

var CountryCodes_034 = /* burkinaFaso : record */[
  /* name */"Burkina Faso",
  /* a2 */"BF",
  /* a3 */"BFA",
  /* num */"854",
  /* dial */"226"
];

var CountryCodes_035 = /* burundi : record */[
  /* name */"Burundi",
  /* a2 */"BI",
  /* a3 */"BDI",
  /* num */"108",
  /* dial */"257"
];

var CountryCodes_036 = /* cambodia : record */[
  /* name */"Cambodia",
  /* a2 */"KH",
  /* a3 */"KHM",
  /* num */"116",
  /* dial */"855"
];

var CountryCodes_037 = /* cameroon : record */[
  /* name */"Cameroon",
  /* a2 */"CM",
  /* a3 */"CMR",
  /* num */"120",
  /* dial */"237"
];

var CountryCodes_038 = /* canada : record */[
  /* name */"Canada",
  /* a2 */"CA",
  /* a3 */"CAN",
  /* num */"124",
  /* dial */"1"
];

var CountryCodes_039 = /* capeVerde : record */[
  /* name */"Cape Verde",
  /* a2 */"CV",
  /* a3 */"CPV",
  /* num */"132",
  /* dial */"238"
];

var CountryCodes_040 = /* caymanIslands : record */[
  /* name */"Cayman Islands",
  /* a2 */"KY",
  /* a3 */"CYM",
  /* num */"136",
  /* dial */"1-345"
];

var CountryCodes_041 = /* centralAfricanRepublic : record */[
  /* name */"Central African Republic",
  /* a2 */"CF",
  /* a3 */"CAF",
  /* num */"140",
  /* dial */"236"
];

var CountryCodes_042 = /* chad : record */[
  /* name */"Chad",
  /* a2 */"TD",
  /* a3 */"TCD",
  /* num */"148",
  /* dial */"235"
];

var CountryCodes_043 = /* chile : record */[
  /* name */"Chile",
  /* a2 */"CL",
  /* a3 */"CHL",
  /* num */"152",
  /* dial */"56"
];

var CountryCodes_044 = /* china : record */[
  /* name */"China",
  /* a2 */"CN",
  /* a3 */"CHN",
  /* num */"156",
  /* dial */"86"
];

var CountryCodes_045 = /* christmasIsland : record */[
  /* name */"Christmas Island",
  /* a2 */"CX",
  /* a3 */"CXR",
  /* num */"162",
  /* dial */"61"
];

var CountryCodes_046 = /* cocosKeelingIslands : record */[
  /* name */"Cocos (Keeling) Islands",
  /* a2 */"CC",
  /* a3 */"CCK",
  /* num */"166",
  /* dial */"61"
];

var CountryCodes_047 = /* colombia : record */[
  /* name */"Colombia",
  /* a2 */"CO",
  /* a3 */"COL",
  /* num */"170",
  /* dial */"57"
];

var CountryCodes_048 = /* comoros : record */[
  /* name */"Comoros",
  /* a2 */"KM",
  /* a3 */"COM",
  /* num */"174",
  /* dial */"269"
];

var CountryCodes_049 = /* congo : record */[
  /* name */"Congo",
  /* a2 */"CG",
  /* a3 */"COG",
  /* num */"178",
  /* dial */"242"
];

var CountryCodes_050 = /* democraticRepublicOfTheCongo : record */[
  /* name */"Democratic Republic of the Congo",
  /* a2 */"CD",
  /* a3 */"COD",
  /* num */"180",
  /* dial */"243"
];

var CountryCodes_051 = /* cookIslands : record */[
  /* name */"Cook Islands",
  /* a2 */"CK",
  /* a3 */"COK",
  /* num */"184",
  /* dial */"682"
];

var CountryCodes_052 = /* costaRica : record */[
  /* name */"Costa Rica",
  /* a2 */"CR",
  /* a3 */"CRI",
  /* num */"188",
  /* dial */"506"
];

var CountryCodes_053 = /* croatia : record */[
  /* name */"Croatia",
  /* a2 */"HR",
  /* a3 */"HRV",
  /* num */"191",
  /* dial */"385"
];

var CountryCodes_054 = /* cuba : record */[
  /* name */"Cuba",
  /* a2 */"CU",
  /* a3 */"CUB",
  /* num */"192",
  /* dial */"53"
];

var CountryCodes_055 = /* curacao : record */[
  /* name */"Curacao",
  /* a2 */"CW",
  /* a3 */"CUW",
  /* num */"531",
  /* dial */"599"
];

var CountryCodes_056 = /* cyprus : record */[
  /* name */"Cyprus",
  /* a2 */"CY",
  /* a3 */"CYP",
  /* num */"196",
  /* dial */"357"
];

var CountryCodes_057 = /* czechRepublic : record */[
  /* name */"Czech Republic",
  /* a2 */"CZ",
  /* a3 */"CZE",
  /* num */"203",
  /* dial */"420"
];

var CountryCodes_058 = /* coteDIvoire : record */[
  /* name */"Cote d'Ivoire",
  /* a2 */"CI",
  /* a3 */"CIV",
  /* num */"384",
  /* dial */"225"
];

var CountryCodes_059 = /* denmark : record */[
  /* name */"Denmark",
  /* a2 */"DK",
  /* a3 */"DNK",
  /* num */"208",
  /* dial */"45"
];

var CountryCodes_060 = /* djibouti : record */[
  /* name */"Djibouti",
  /* a2 */"DJ",
  /* a3 */"DJI",
  /* num */"262",
  /* dial */"253"
];

var CountryCodes_061 = /* dominica : record */[
  /* name */"Dominica",
  /* a2 */"DM",
  /* a3 */"DMA",
  /* num */"212",
  /* dial */"1-767"
];

var CountryCodes_062 = /* dominicanRepublic : record */[
  /* name */"Dominican Republic",
  /* a2 */"DO",
  /* a3 */"DOM",
  /* num */"214",
  /* dial */"1-809,1-829,1-849"
];

var CountryCodes_063 = /* ecuador : record */[
  /* name */"Ecuador",
  /* a2 */"EC",
  /* a3 */"ECU",
  /* num */"218",
  /* dial */"593"
];

var CountryCodes_064 = /* egypt : record */[
  /* name */"Egypt",
  /* a2 */"EG",
  /* a3 */"EGY",
  /* num */"818",
  /* dial */"20"
];

var CountryCodes_065 = /* elSalvador : record */[
  /* name */"El Salvador",
  /* a2 */"SV",
  /* a3 */"SLV",
  /* num */"222",
  /* dial */"503"
];

var CountryCodes_066 = /* equatorialGuinea : record */[
  /* name */"Equatorial Guinea",
  /* a2 */"GQ",
  /* a3 */"GNQ",
  /* num */"226",
  /* dial */"240"
];

var CountryCodes_067 = /* eritrea : record */[
  /* name */"Eritrea",
  /* a2 */"ER",
  /* a3 */"ERI",
  /* num */"232",
  /* dial */"291"
];

var CountryCodes_068 = /* estonia : record */[
  /* name */"Estonia",
  /* a2 */"EE",
  /* a3 */"EST",
  /* num */"233",
  /* dial */"372"
];

var CountryCodes_069 = /* ethiopia : record */[
  /* name */"Ethiopia",
  /* a2 */"ET",
  /* a3 */"ETH",
  /* num */"231",
  /* dial */"251"
];

var CountryCodes_070 = /* falklandIslandsMalvinas : record */[
  /* name */"Falkland Islands (Malvinas)",
  /* a2 */"FK",
  /* a3 */"FLK",
  /* num */"238",
  /* dial */"500"
];

var CountryCodes_071 = /* faroeIslands : record */[
  /* name */"Faroe Islands",
  /* a2 */"FO",
  /* a3 */"FRO",
  /* num */"234",
  /* dial */"298"
];

var CountryCodes_072 = /* fiji : record */[
  /* name */"Fiji",
  /* a2 */"FJ",
  /* a3 */"FJI",
  /* num */"242",
  /* dial */"679"
];

var CountryCodes_073 = /* finland : record */[
  /* name */"Finland",
  /* a2 */"FI",
  /* a3 */"FIN",
  /* num */"246",
  /* dial */"358"
];

var CountryCodes_074 = /* france : record */[
  /* name */"France",
  /* a2 */"FR",
  /* a3 */"FRA",
  /* num */"250",
  /* dial */"33"
];

var CountryCodes_075 = /* frenchGuiana : record */[
  /* name */"French Guiana",
  /* a2 */"GF",
  /* a3 */"GUF",
  /* num */"254",
  /* dial */"594"
];

var CountryCodes_076 = /* frenchPolynesia : record */[
  /* name */"French Polynesia",
  /* a2 */"PF",
  /* a3 */"PYF",
  /* num */"258",
  /* dial */"689"
];

var CountryCodes_077 = /* frenchSouthernTerritories : record */[
  /* name */"French Southern Territories",
  /* a2 */"TF",
  /* a3 */"ATF",
  /* num */"260",
  /* dial */"262"
];

var CountryCodes_078 = /* gabon : record */[
  /* name */"Gabon",
  /* a2 */"GA",
  /* a3 */"GAB",
  /* num */"266",
  /* dial */"241"
];

var CountryCodes_079 = /* gambia : record */[
  /* name */"Gambia",
  /* a2 */"GM",
  /* a3 */"GMB",
  /* num */"270",
  /* dial */"220"
];

var CountryCodes_080 = /* georgia : record */[
  /* name */"Georgia",
  /* a2 */"GE",
  /* a3 */"GEO",
  /* num */"268",
  /* dial */"995"
];

var CountryCodes_081 = /* germany : record */[
  /* name */"Germany",
  /* a2 */"DE",
  /* a3 */"DEU",
  /* num */"276",
  /* dial */"49"
];

var CountryCodes_082 = /* ghana : record */[
  /* name */"Ghana",
  /* a2 */"GH",
  /* a3 */"GHA",
  /* num */"288",
  /* dial */"233"
];

var CountryCodes_083 = /* gibraltar : record */[
  /* name */"Gibraltar",
  /* a2 */"GI",
  /* a3 */"GIB",
  /* num */"292",
  /* dial */"350"
];

var CountryCodes_084 = /* greece : record */[
  /* name */"Greece",
  /* a2 */"GR",
  /* a3 */"GRC",
  /* num */"300",
  /* dial */"30"
];

var CountryCodes_085 = /* greenland : record */[
  /* name */"Greenland",
  /* a2 */"GL",
  /* a3 */"GRL",
  /* num */"304",
  /* dial */"299"
];

var CountryCodes_086 = /* grenada : record */[
  /* name */"Grenada",
  /* a2 */"GD",
  /* a3 */"GRD",
  /* num */"308",
  /* dial */"1-473"
];

var CountryCodes_087 = /* guadeloupe : record */[
  /* name */"Guadeloupe",
  /* a2 */"GP",
  /* a3 */"GLP",
  /* num */"312",
  /* dial */"590"
];

var CountryCodes_088 = /* guam : record */[
  /* name */"Guam",
  /* a2 */"GU",
  /* a3 */"GUM",
  /* num */"316",
  /* dial */"1-671"
];

var CountryCodes_089 = /* guatemala : record */[
  /* name */"Guatemala",
  /* a2 */"GT",
  /* a3 */"GTM",
  /* num */"320",
  /* dial */"502"
];

var CountryCodes_090 = /* guernsey : record */[
  /* name */"Guernsey",
  /* a2 */"GG",
  /* a3 */"GGY",
  /* num */"831",
  /* dial */"44"
];

var CountryCodes_091 = /* guinea : record */[
  /* name */"Guinea",
  /* a2 */"GN",
  /* a3 */"GIN",
  /* num */"324",
  /* dial */"224"
];

var CountryCodes_092 = /* guineaBissau : record */[
  /* name */"Guinea-Bissau",
  /* a2 */"GW",
  /* a3 */"GNB",
  /* num */"624",
  /* dial */"245"
];

var CountryCodes_093 = /* guyana : record */[
  /* name */"Guyana",
  /* a2 */"GY",
  /* a3 */"GUY",
  /* num */"328",
  /* dial */"592"
];

var CountryCodes_094 = /* haiti : record */[
  /* name */"Haiti",
  /* a2 */"HT",
  /* a3 */"HTI",
  /* num */"332",
  /* dial */"509"
];

var CountryCodes_095 = /* heardIslandAndMcDonaldIslands : record */[
  /* name */"Heard Island and McDonald Islands",
  /* a2 */"HM",
  /* a3 */"HMD",
  /* num */"334",
  /* dial */"672"
];

var CountryCodes_096 = /* honduras : record */[
  /* name */"Honduras",
  /* a2 */"HN",
  /* a3 */"HND",
  /* num */"340",
  /* dial */"504"
];

var CountryCodes_097 = /* hongKong : record */[
  /* name */"Hong Kong",
  /* a2 */"HK",
  /* a3 */"HKG",
  /* num */"344",
  /* dial */"852"
];

var CountryCodes_098 = /* hungary : record */[
  /* name */"Hungary",
  /* a2 */"HU",
  /* a3 */"HUN",
  /* num */"348",
  /* dial */"36"
];

var CountryCodes_099 = /* iceland : record */[
  /* name */"Iceland",
  /* a2 */"IS",
  /* a3 */"ISL",
  /* num */"352",
  /* dial */"354"
];

var CountryCodes_100 = /* india : record */[
  /* name */"India",
  /* a2 */"IN",
  /* a3 */"IND",
  /* num */"356",
  /* dial */"91"
];

var CountryCodes_101 = /* indonesia : record */[
  /* name */"Indonesia",
  /* a2 */"ID",
  /* a3 */"IDN",
  /* num */"360",
  /* dial */"62"
];

var CountryCodes_102 = /* iran : record */[
  /* name */"Iran, Islamic Republic of",
  /* a2 */"IR",
  /* a3 */"IRN",
  /* num */"364",
  /* dial */"98"
];

var CountryCodes_103 = /* iraq : record */[
  /* name */"Iraq",
  /* a2 */"IQ",
  /* a3 */"IRQ",
  /* num */"368",
  /* dial */"964"
];

var CountryCodes_104 = /* ireland : record */[
  /* name */"Ireland",
  /* a2 */"IE",
  /* a3 */"IRL",
  /* num */"372",
  /* dial */"353"
];

var CountryCodes_105 = /* isleofMan : record */[
  /* name */"Isle of Man",
  /* a2 */"IM",
  /* a3 */"IMN",
  /* num */"833",
  /* dial */"44"
];

var CountryCodes_106 = /* israel : record */[
  /* name */"Israel",
  /* a2 */"IL",
  /* a3 */"ISR",
  /* num */"376",
  /* dial */"972"
];

var CountryCodes_107 = /* italy : record */[
  /* name */"Italy",
  /* a2 */"IT",
  /* a3 */"ITA",
  /* num */"380",
  /* dial */"39"
];

var CountryCodes_108 = /* jamaica : record */[
  /* name */"Jamaica",
  /* a2 */"JM",
  /* a3 */"JAM",
  /* num */"388",
  /* dial */"1-876"
];

var CountryCodes_109 = /* japan : record */[
  /* name */"Japan",
  /* a2 */"JP",
  /* a3 */"JPN",
  /* num */"392",
  /* dial */"81"
];

var CountryCodes_110 = /* jersey : record */[
  /* name */"Jersey",
  /* a2 */"JE",
  /* a3 */"JEY",
  /* num */"832",
  /* dial */"44"
];

var CountryCodes_111 = /* jordan : record */[
  /* name */"Jordan",
  /* a2 */"JO",
  /* a3 */"JOR",
  /* num */"400",
  /* dial */"962"
];

var CountryCodes_112 = /* kazakhstan : record */[
  /* name */"Kazakhstan",
  /* a2 */"KZ",
  /* a3 */"KAZ",
  /* num */"398",
  /* dial */"7"
];

var CountryCodes_113 = /* kenya : record */[
  /* name */"Kenya",
  /* a2 */"KE",
  /* a3 */"KEN",
  /* num */"404",
  /* dial */"254"
];

var CountryCodes_114 = /* kiribati : record */[
  /* name */"Kiribati",
  /* a2 */"KI",
  /* a3 */"KIR",
  /* num */"296",
  /* dial */"686"
];

var CountryCodes_115 = /* northKorea : record */[
  /* name */"Korea, Democratic People's Republic of",
  /* a2 */"KP",
  /* a3 */"PRK",
  /* num */"408",
  /* dial */"850"
];

var CountryCodes_116 = /* southKorea : record */[
  /* name */"Korea, Republic of",
  /* a2 */"KR",
  /* a3 */"KOR",
  /* num */"410",
  /* dial */"82"
];

var CountryCodes_117 = /* kuwait : record */[
  /* name */"Kuwait",
  /* a2 */"KW",
  /* a3 */"KWT",
  /* num */"414",
  /* dial */"965"
];

var CountryCodes_118 = /* kyrgyzstan : record */[
  /* name */"Kyrgyzstan",
  /* a2 */"KG",
  /* a3 */"KGZ",
  /* num */"417",
  /* dial */"996"
];

var CountryCodes_119 = /* lao : record */[
  /* name */"Lao People's Democratic Republic",
  /* a2 */"LA",
  /* a3 */"LAO",
  /* num */"418",
  /* dial */"856"
];

var CountryCodes_120 = /* latvia : record */[
  /* name */"Latvia",
  /* a2 */"LV",
  /* a3 */"LVA",
  /* num */"428",
  /* dial */"371"
];

var CountryCodes_121 = /* lebanon : record */[
  /* name */"Lebanon",
  /* a2 */"LB",
  /* a3 */"LBN",
  /* num */"422",
  /* dial */"961"
];

var CountryCodes_122 = /* lesotho : record */[
  /* name */"Lesotho",
  /* a2 */"LS",
  /* a3 */"LSO",
  /* num */"426",
  /* dial */"266"
];

var CountryCodes_123 = /* liberia : record */[
  /* name */"Liberia",
  /* a2 */"LR",
  /* a3 */"LBR",
  /* num */"430",
  /* dial */"231"
];

var CountryCodes_124 = /* libya : record */[
  /* name */"Libya",
  /* a2 */"LY",
  /* a3 */"LBY",
  /* num */"434",
  /* dial */"218"
];

var CountryCodes_125 = /* liechtenstein : record */[
  /* name */"Liechtenstein",
  /* a2 */"LI",
  /* a3 */"LIE",
  /* num */"438",
  /* dial */"423"
];

var CountryCodes_126 = /* lithuania : record */[
  /* name */"Lithuania",
  /* a2 */"LT",
  /* a3 */"LTU",
  /* num */"440",
  /* dial */"370"
];

var CountryCodes_127 = /* luxembourg : record */[
  /* name */"Luxembourg",
  /* a2 */"LU",
  /* a3 */"LUX",
  /* num */"442",
  /* dial */"352"
];

var CountryCodes_128 = /* macao : record */[
  /* name */"Macao",
  /* a2 */"MO",
  /* a3 */"MAC",
  /* num */"446",
  /* dial */"853"
];

var CountryCodes_129 = /* macedonia : record */[
  /* name */"Macedonia, the Former Yugoslav Republic of",
  /* a2 */"MK",
  /* a3 */"MKD",
  /* num */"807",
  /* dial */"389"
];

var CountryCodes_130 = /* madagascar : record */[
  /* name */"Madagascar",
  /* a2 */"MG",
  /* a3 */"MDG",
  /* num */"450",
  /* dial */"261"
];

var CountryCodes_131 = /* malawi : record */[
  /* name */"Malawi",
  /* a2 */"MW",
  /* a3 */"MWI",
  /* num */"454",
  /* dial */"265"
];

var CountryCodes_132 = /* malaysia : record */[
  /* name */"Malaysia",
  /* a2 */"MY",
  /* a3 */"MYS",
  /* num */"458",
  /* dial */"60"
];

var CountryCodes_133 = /* maldives : record */[
  /* name */"Maldives",
  /* a2 */"MV",
  /* a3 */"MDV",
  /* num */"462",
  /* dial */"960"
];

var CountryCodes_134 = /* mali : record */[
  /* name */"Mali",
  /* a2 */"ML",
  /* a3 */"MLI",
  /* num */"466",
  /* dial */"223"
];

var CountryCodes_135 = /* malta : record */[
  /* name */"Malta",
  /* a2 */"MT",
  /* a3 */"MLT",
  /* num */"470",
  /* dial */"356"
];

var CountryCodes_136 = /* marshallIslands : record */[
  /* name */"Marshall Islands",
  /* a2 */"MH",
  /* a3 */"MHL",
  /* num */"584",
  /* dial */"692"
];

var CountryCodes_137 = /* martinique : record */[
  /* name */"Martinique",
  /* a2 */"MQ",
  /* a3 */"MTQ",
  /* num */"474",
  /* dial */"596"
];

var CountryCodes_138 = /* mauritania : record */[
  /* name */"Mauritania",
  /* a2 */"MR",
  /* a3 */"MRT",
  /* num */"478",
  /* dial */"222"
];

var CountryCodes_139 = /* mauritius : record */[
  /* name */"Mauritius",
  /* a2 */"MU",
  /* a3 */"MUS",
  /* num */"480",
  /* dial */"230"
];

var CountryCodes_140 = /* mayotte : record */[
  /* name */"Mayotte",
  /* a2 */"YT",
  /* a3 */"MYT",
  /* num */"175",
  /* dial */"262"
];

var CountryCodes_141 = /* mexico : record */[
  /* name */"Mexico",
  /* a2 */"MX",
  /* a3 */"MEX",
  /* num */"484",
  /* dial */"52"
];

var CountryCodes_142 = /* micronesia : record */[
  /* name */"Micronesia, Federated States of",
  /* a2 */"FM",
  /* a3 */"FSM",
  /* num */"583",
  /* dial */"691"
];

var CountryCodes_143 = /* moldova : record */[
  /* name */"Moldova, Republic of",
  /* a2 */"MD",
  /* a3 */"MDA",
  /* num */"498",
  /* dial */"373"
];

var CountryCodes_144 = /* monaco : record */[
  /* name */"Monaco",
  /* a2 */"MC",
  /* a3 */"MCO",
  /* num */"492",
  /* dial */"377"
];

var CountryCodes_145 = /* mongolia : record */[
  /* name */"Mongolia",
  /* a2 */"MN",
  /* a3 */"MNG",
  /* num */"496",
  /* dial */"976"
];

var CountryCodes_146 = /* montenegro : record */[
  /* name */"Montenegro",
  /* a2 */"ME",
  /* a3 */"MNE",
  /* num */"499",
  /* dial */"382"
];

var CountryCodes_147 = /* montserrat : record */[
  /* name */"Montserrat",
  /* a2 */"MS",
  /* a3 */"MSR",
  /* num */"500",
  /* dial */"1-664"
];

var CountryCodes_148 = /* morocco : record */[
  /* name */"Morocco",
  /* a2 */"MA",
  /* a3 */"MAR",
  /* num */"504",
  /* dial */"212"
];

var CountryCodes_149 = /* mozambique : record */[
  /* name */"Mozambique",
  /* a2 */"MZ",
  /* a3 */"MOZ",
  /* num */"508",
  /* dial */"258"
];

var CountryCodes_150 = /* myanmar : record */[
  /* name */"Myanmar",
  /* a2 */"MM",
  /* a3 */"MMR",
  /* num */"104",
  /* dial */"95"
];

var CountryCodes_151 = /* namibia : record */[
  /* name */"Namibia",
  /* a2 */"NA",
  /* a3 */"NAM",
  /* num */"516",
  /* dial */"264"
];

var CountryCodes_152 = /* nauru : record */[
  /* name */"Nauru",
  /* a2 */"NR",
  /* a3 */"NRU",
  /* num */"520",
  /* dial */"674"
];

var CountryCodes_153 = /* nepal : record */[
  /* name */"Nepal",
  /* a2 */"NP",
  /* a3 */"NPL",
  /* num */"524",
  /* dial */"977"
];

var CountryCodes_154 = /* netherlands : record */[
  /* name */"Netherlands",
  /* a2 */"NL",
  /* a3 */"NLD",
  /* num */"528",
  /* dial */"31"
];

var CountryCodes_155 = /* newCaledonia : record */[
  /* name */"New Caledonia",
  /* a2 */"NC",
  /* a3 */"NCL",
  /* num */"540",
  /* dial */"687"
];

var CountryCodes_156 = /* newZealand : record */[
  /* name */"New Zealand",
  /* a2 */"NZ",
  /* a3 */"NZL",
  /* num */"554",
  /* dial */"64"
];

var CountryCodes_157 = /* nicaragua : record */[
  /* name */"Nicaragua",
  /* a2 */"NI",
  /* a3 */"NIC",
  /* num */"558",
  /* dial */"505"
];

var CountryCodes_158 = /* niger : record */[
  /* name */"Niger",
  /* a2 */"NE",
  /* a3 */"NER",
  /* num */"562",
  /* dial */"227"
];

var CountryCodes_159 = /* nigeria : record */[
  /* name */"Nigeria",
  /* a2 */"NG",
  /* a3 */"NGA",
  /* num */"566",
  /* dial */"234"
];

var CountryCodes_160 = /* niue : record */[
  /* name */"Niue",
  /* a2 */"NU",
  /* a3 */"NIU",
  /* num */"570",
  /* dial */"683"
];

var CountryCodes_161 = /* norfolkIsland : record */[
  /* name */"Norfolk Island",
  /* a2 */"NF",
  /* a3 */"NFK",
  /* num */"574",
  /* dial */"672"
];

var CountryCodes_162 = /* northernMarianaIslands : record */[
  /* name */"Northern Mariana Islands",
  /* a2 */"MP",
  /* a3 */"MNP",
  /* num */"580",
  /* dial */"1-670"
];

var CountryCodes_163 = /* norway : record */[
  /* name */"Norway",
  /* a2 */"NO",
  /* a3 */"NOR",
  /* num */"578",
  /* dial */"47"
];

var CountryCodes_164 = /* oman : record */[
  /* name */"Oman",
  /* a2 */"OM",
  /* a3 */"OMN",
  /* num */"512",
  /* dial */"968"
];

var CountryCodes_165 = /* pakistan : record */[
  /* name */"Pakistan",
  /* a2 */"PK",
  /* a3 */"PAK",
  /* num */"586",
  /* dial */"92"
];

var CountryCodes_166 = /* palau : record */[
  /* name */"Palau",
  /* a2 */"PW",
  /* a3 */"PLW",
  /* num */"585",
  /* dial */"680"
];

var CountryCodes_167 = /* palestine : record */[
  /* name */"Palestine, State of",
  /* a2 */"PS",
  /* a3 */"PSE",
  /* num */"275",
  /* dial */"970"
];

var CountryCodes_168 = /* panama : record */[
  /* name */"Panama",
  /* a2 */"PA",
  /* a3 */"PAN",
  /* num */"591",
  /* dial */"507"
];

var CountryCodes_169 = /* papuaNewGuinea : record */[
  /* name */"Papua New Guinea",
  /* a2 */"PG",
  /* a3 */"PNG",
  /* num */"598",
  /* dial */"675"
];

var CountryCodes_170 = /* paraguay : record */[
  /* name */"Paraguay",
  /* a2 */"PY",
  /* a3 */"PRY",
  /* num */"600",
  /* dial */"595"
];

var CountryCodes_171 = /* peru : record */[
  /* name */"Peru",
  /* a2 */"PE",
  /* a3 */"PER",
  /* num */"604",
  /* dial */"51"
];

var CountryCodes_172 = /* philippines : record */[
  /* name */"Philippines",
  /* a2 */"PH",
  /* a3 */"PHL",
  /* num */"608",
  /* dial */"63"
];

var CountryCodes_173 = /* pitcairn : record */[
  /* name */"Pitcairn",
  /* a2 */"PN",
  /* a3 */"PCN",
  /* num */"612",
  /* dial */"870"
];

var CountryCodes_174 = /* poland : record */[
  /* name */"Poland",
  /* a2 */"PL",
  /* a3 */"POL",
  /* num */"616",
  /* dial */"48"
];

var CountryCodes_175 = /* portugal : record */[
  /* name */"Portugal",
  /* a2 */"PT",
  /* a3 */"PRT",
  /* num */"620",
  /* dial */"351"
];

var CountryCodes_176 = /* puertoRico : record */[
  /* name */"Puerto Rico",
  /* a2 */"PR",
  /* a3 */"PRI",
  /* num */"630",
  /* dial */"1"
];

var CountryCodes_177 = /* qatar : record */[
  /* name */"Qatar",
  /* a2 */"QA",
  /* a3 */"QAT",
  /* num */"634",
  /* dial */"974"
];

var CountryCodes_178 = /* romania : record */[
  /* name */"Romania",
  /* a2 */"RO",
  /* a3 */"ROU",
  /* num */"642",
  /* dial */"40"
];

var CountryCodes_179 = /* russianFederation : record */[
  /* name */"Russian Federation",
  /* a2 */"RU",
  /* a3 */"RUS",
  /* num */"643",
  /* dial */"7"
];

var CountryCodes_180 = /* rwanda : record */[
  /* name */"Rwanda",
  /* a2 */"RW",
  /* a3 */"RWA",
  /* num */"646",
  /* dial */"250"
];

var CountryCodes_181 = /* reunion : record */[
  /* name */"Reunion",
  /* a2 */"RE",
  /* a3 */"REU",
  /* num */"638",
  /* dial */"262"
];

var CountryCodes_182 = /* saintBarthelemy : record */[
  /* name */"Saint Barthelemy",
  /* a2 */"BL",
  /* a3 */"BLM",
  /* num */"652",
  /* dial */"590"
];

var CountryCodes_183 = /* saintHelena : record */[
  /* name */"Saint Helena",
  /* a2 */"SH",
  /* a3 */"SHN",
  /* num */"654",
  /* dial */"290"
];

var CountryCodes_184 = /* saintKittsAndNevis : record */[
  /* name */"Saint Kitts and Nevis",
  /* a2 */"KN",
  /* a3 */"KNA",
  /* num */"659",
  /* dial */"1-869"
];

var CountryCodes_185 = /* saintLucia : record */[
  /* name */"Saint Lucia",
  /* a2 */"LC",
  /* a3 */"LCA",
  /* num */"662",
  /* dial */"1-758"
];

var CountryCodes_186 = /* saintMartinFrenchPart : record */[
  /* name */"Saint Martin (French part)",
  /* a2 */"MF",
  /* a3 */"MAF",
  /* num */"663",
  /* dial */"590"
];

var CountryCodes_187 = /* saintPierreAndMiquelon : record */[
  /* name */"Saint Pierre and Miquelon",
  /* a2 */"PM",
  /* a3 */"SPM",
  /* num */"666",
  /* dial */"508"
];

var CountryCodes_188 = /* saintVincentAndtheGrenadines : record */[
  /* name */"Saint Vincent and the Grenadines",
  /* a2 */"VC",
  /* a3 */"VCT",
  /* num */"670",
  /* dial */"1-784"
];

var CountryCodes_189 = /* samoa : record */[
  /* name */"Samoa",
  /* a2 */"WS",
  /* a3 */"WSM",
  /* num */"882",
  /* dial */"685"
];

var CountryCodes_190 = /* sanMarino : record */[
  /* name */"San Marino",
  /* a2 */"SM",
  /* a3 */"SMR",
  /* num */"674",
  /* dial */"378"
];

var CountryCodes_191 = /* saoTomeAndPrincipe : record */[
  /* name */"Sao Tome and Principe",
  /* a2 */"ST",
  /* a3 */"STP",
  /* num */"678",
  /* dial */"239"
];

var CountryCodes_192 = /* saudiArabia : record */[
  /* name */"Saudi Arabia",
  /* a2 */"SA",
  /* a3 */"SAU",
  /* num */"682",
  /* dial */"966"
];

var CountryCodes_193 = /* senegal : record */[
  /* name */"Senegal",
  /* a2 */"SN",
  /* a3 */"SEN",
  /* num */"686",
  /* dial */"221"
];

var CountryCodes_194 = /* serbia : record */[
  /* name */"Serbia",
  /* a2 */"RS",
  /* a3 */"SRB",
  /* num */"688",
  /* dial */"381"
];

var CountryCodes_195 = /* seychelles : record */[
  /* name */"Seychelles",
  /* a2 */"SC",
  /* a3 */"SYC",
  /* num */"690",
  /* dial */"248"
];

var CountryCodes_196 = /* sierraLeone : record */[
  /* name */"Sierra Leone",
  /* a2 */"SL",
  /* a3 */"SLE",
  /* num */"694",
  /* dial */"232"
];

var CountryCodes_197 = /* singapore : record */[
  /* name */"Singapore",
  /* a2 */"SG",
  /* a3 */"SGP",
  /* num */"702",
  /* dial */"65"
];

var CountryCodes_198 = /* sintMaartenDutchPart : record */[
  /* name */"Sint Maarten (Dutch part)",
  /* a2 */"SX",
  /* a3 */"SXM",
  /* num */"534",
  /* dial */"1-721"
];

var CountryCodes_199 = /* slovakia : record */[
  /* name */"Slovakia",
  /* a2 */"SK",
  /* a3 */"SVK",
  /* num */"703",
  /* dial */"421"
];

var CountryCodes_200 = /* slovenia : record */[
  /* name */"Slovenia",
  /* a2 */"SI",
  /* a3 */"SVN",
  /* num */"705",
  /* dial */"386"
];

var CountryCodes_201 = /* solomonIslands : record */[
  /* name */"Solomon Islands",
  /* a2 */"SB",
  /* a3 */"SLB",
  /* num */"90",
  /* dial */"677"
];

var CountryCodes_202 = /* somalia : record */[
  /* name */"Somalia",
  /* a2 */"SO",
  /* a3 */"SOM",
  /* num */"706",
  /* dial */"252"
];

var CountryCodes_203 = /* southAfrica : record */[
  /* name */"South Africa",
  /* a2 */"ZA",
  /* a3 */"ZAF",
  /* num */"710",
  /* dial */"27"
];

var CountryCodes_204 = /* southGeorgiaAndtheSouthSandwichIslands : record */[
  /* name */"South Georgia and the South Sandwich Islands",
  /* a2 */"GS",
  /* a3 */"SGS",
  /* num */"239",
  /* dial */"500"
];

var CountryCodes_205 = /* southSudan : record */[
  /* name */"South Sudan",
  /* a2 */"SS",
  /* a3 */"SSD",
  /* num */"728",
  /* dial */"211"
];

var CountryCodes_206 = /* spain : record */[
  /* name */"Spain",
  /* a2 */"ES",
  /* a3 */"ESP",
  /* num */"724",
  /* dial */"34"
];

var CountryCodes_207 = /* sriLanka : record */[
  /* name */"Sri Lanka",
  /* a2 */"LK",
  /* a3 */"LKA",
  /* num */"144",
  /* dial */"94"
];

var CountryCodes_208 = /* sudan : record */[
  /* name */"Sudan",
  /* a2 */"SD",
  /* a3 */"SDN",
  /* num */"729",
  /* dial */"249"
];

var CountryCodes_209 = /* suriname : record */[
  /* name */"Suriname",
  /* a2 */"SR",
  /* a3 */"SUR",
  /* num */"740",
  /* dial */"597"
];

var CountryCodes_210 = /* svalbardAndJanMayen : record */[
  /* name */"Svalbard and Jan Mayen",
  /* a2 */"SJ",
  /* a3 */"SJM",
  /* num */"744",
  /* dial */"47"
];

var CountryCodes_211 = /* swaziland : record */[
  /* name */"Swaziland",
  /* a2 */"SZ",
  /* a3 */"SWZ",
  /* num */"748",
  /* dial */"268"
];

var CountryCodes_212 = /* sweden : record */[
  /* name */"Sweden",
  /* a2 */"SE",
  /* a3 */"SWE",
  /* num */"752",
  /* dial */"46"
];

var CountryCodes_213 = /* switzerland : record */[
  /* name */"Switzerland",
  /* a2 */"CH",
  /* a3 */"CHE",
  /* num */"756",
  /* dial */"41"
];

var CountryCodes_214 = /* syrianArabRepublic : record */[
  /* name */"Syrian Arab Republic",
  /* a2 */"SY",
  /* a3 */"SYR",
  /* num */"760",
  /* dial */"963"
];

var CountryCodes_215 = /* taiwan : record */[
  /* name */"Taiwan",
  /* a2 */"TW",
  /* a3 */"TWN",
  /* num */"158",
  /* dial */"886"
];

var CountryCodes_216 = /* tajikistan : record */[
  /* name */"Tajikistan",
  /* a2 */"TJ",
  /* a3 */"TJK",
  /* num */"762",
  /* dial */"992"
];

var CountryCodes_217 = /* unitedRepublicOfTanzania : record */[
  /* name */"United Republic of Tanzania",
  /* a2 */"TZ",
  /* a3 */"TZA",
  /* num */"834",
  /* dial */"255"
];

var CountryCodes_218 = /* thailand : record */[
  /* name */"Thailand",
  /* a2 */"TH",
  /* a3 */"THA",
  /* num */"764",
  /* dial */"66"
];

var CountryCodes_219 = /* timorLeste : record */[
  /* name */"Timor-Leste",
  /* a2 */"TL",
  /* a3 */"TLS",
  /* num */"626",
  /* dial */"670"
];

var CountryCodes_220 = /* togo : record */[
  /* name */"Togo",
  /* a2 */"TG",
  /* a3 */"TGO",
  /* num */"768",
  /* dial */"228"
];

var CountryCodes_221 = /* tokelau : record */[
  /* name */"Tokelau",
  /* a2 */"TK",
  /* a3 */"TKL",
  /* num */"772",
  /* dial */"690"
];

var CountryCodes_222 = /* tonga : record */[
  /* name */"Tonga",
  /* a2 */"TO",
  /* a3 */"TON",
  /* num */"776",
  /* dial */"676"
];

var CountryCodes_223 = /* trinidadAndTobago : record */[
  /* name */"Trinidad and Tobago",
  /* a2 */"TT",
  /* a3 */"TTO",
  /* num */"780",
  /* dial */"1-868"
];

var CountryCodes_224 = /* tunisia : record */[
  /* name */"Tunisia",
  /* a2 */"TN",
  /* a3 */"TUN",
  /* num */"788",
  /* dial */"216"
];

var CountryCodes_225 = /* turkey : record */[
  /* name */"Turkey",
  /* a2 */"TR",
  /* a3 */"TUR",
  /* num */"792",
  /* dial */"90"
];

var CountryCodes_226 = /* turkmenistan : record */[
  /* name */"Turkmenistan",
  /* a2 */"TM",
  /* a3 */"TKM",
  /* num */"795",
  /* dial */"993"
];

var CountryCodes_227 = /* turksandCaicosIslands : record */[
  /* name */"Turks and Caicos Islands",
  /* a2 */"TC",
  /* a3 */"TCA",
  /* num */"796",
  /* dial */"1-649"
];

var CountryCodes_228 = /* tuvalu : record */[
  /* name */"Tuvalu",
  /* a2 */"TV",
  /* a3 */"TUV",
  /* num */"798",
  /* dial */"688"
];

var CountryCodes_229 = /* uganda : record */[
  /* name */"Uganda",
  /* a2 */"UG",
  /* a3 */"UGA",
  /* num */"800",
  /* dial */"256"
];

var CountryCodes_230 = /* ukraine : record */[
  /* name */"Ukraine",
  /* a2 */"UA",
  /* a3 */"UKR",
  /* num */"804",
  /* dial */"380"
];

var CountryCodes_231 = /* unitedArabEmirates : record */[
  /* name */"United Arab Emirates",
  /* a2 */"AE",
  /* a3 */"ARE",
  /* num */"784",
  /* dial */"971"
];

var CountryCodes_232 = /* unitedKingdom : record */[
  /* name */"United Kingdom",
  /* a2 */"GB",
  /* a3 */"GBR",
  /* num */"826",
  /* dial */"44"
];

var CountryCodes_233 = /* unitedStates : record */[
  /* name */"United States",
  /* a2 */"US",
  /* a3 */"USA",
  /* num */"840",
  /* dial */"1"
];

var CountryCodes_234 = /* unitedStatesMinorOutlyingIslands : record */[
  /* name */"United States Minor Outlying Islands",
  /* a2 */"UM",
  /* a3 */"UMI",
  /* num */"581",
  /* dial */"1"
];

var CountryCodes_235 = /* uruguay : record */[
  /* name */"Uruguay",
  /* a2 */"UY",
  /* a3 */"URY",
  /* num */"858",
  /* dial */"598"
];

var CountryCodes_236 = /* uzbekistan : record */[
  /* name */"Uzbekistan",
  /* a2 */"UZ",
  /* a3 */"UZB",
  /* num */"860",
  /* dial */"998"
];

var CountryCodes_237 = /* vanuatu : record */[
  /* name */"Vanuatu",
  /* a2 */"VU",
  /* a3 */"VUT",
  /* num */"548",
  /* dial */"678"
];

var CountryCodes_238 = /* vaticanCityState : record */[
  /* name */"Holy See (Vatican City State)",
  /* a2 */"VA",
  /* a3 */"VAT",
  /* num */"336",
  /* dial */"379"
];

var CountryCodes_239 = /* venezuela : record */[
  /* name */"Venezuela",
  /* a2 */"VE",
  /* a3 */"VEN",
  /* num */"862",
  /* dial */"58"
];

var CountryCodes_240 = /* vietNam : record */[
  /* name */"Viet Nam",
  /* a2 */"VN",
  /* a3 */"VNM",
  /* num */"704",
  /* dial */"84"
];

var CountryCodes_241 = /* britishVirginIslands : record */[
  /* name */"British Virgin Islands",
  /* a2 */"VG",
  /* a3 */"VGB",
  /* num */"92",
  /* dial */"1-284"
];

var CountryCodes_242 = /* usVirginIslands : record */[
  /* name */"US Virgin Islands",
  /* a2 */"VI",
  /* a3 */"VIR",
  /* num */"850",
  /* dial */"1-340"
];

var CountryCodes_243 = /* wallisAndFutuna : record */[
  /* name */"Wallis and Futuna",
  /* a2 */"WF",
  /* a3 */"WLF",
  /* num */"876",
  /* dial */"681"
];

var CountryCodes_244 = /* westernSahara : record */[
  /* name */"Western Sahara",
  /* a2 */"EH",
  /* a3 */"ESH",
  /* num */"732",
  /* dial */"212"
];

var CountryCodes_245 = /* yemen : record */[
  /* name */"Yemen",
  /* a2 */"YE",
  /* a3 */"YEM",
  /* num */"887",
  /* dial */"967"
];

var CountryCodes_246 = /* zambia : record */[
  /* name */"Zambia",
  /* a2 */"ZM",
  /* a3 */"ZMB",
  /* num */"894",
  /* dial */"260"
];

var CountryCodes_247 = /* zimbabwe : record */[
  /* name */"Zimbabwe",
  /* a2 */"ZW",
  /* a3 */"ZWE",
  /* num */"716",
  /* dial */"263"
];

var CountryCodes = /* module */[
  CountryCodes_000,
  CountryCodes_001,
  CountryCodes_002,
  CountryCodes_003,
  CountryCodes_004,
  CountryCodes_005,
  CountryCodes_006,
  CountryCodes_007,
  CountryCodes_008,
  CountryCodes_009,
  CountryCodes_010,
  CountryCodes_011,
  CountryCodes_012,
  CountryCodes_013,
  CountryCodes_014,
  CountryCodes_015,
  CountryCodes_016,
  CountryCodes_017,
  CountryCodes_018,
  CountryCodes_019,
  CountryCodes_020,
  CountryCodes_021,
  CountryCodes_022,
  CountryCodes_023,
  CountryCodes_024,
  CountryCodes_025,
  CountryCodes_026,
  CountryCodes_027,
  CountryCodes_028,
  CountryCodes_029,
  CountryCodes_030,
  CountryCodes_031,
  CountryCodes_032,
  CountryCodes_033,
  CountryCodes_034,
  CountryCodes_035,
  CountryCodes_036,
  CountryCodes_037,
  CountryCodes_038,
  CountryCodes_039,
  CountryCodes_040,
  CountryCodes_041,
  CountryCodes_042,
  CountryCodes_043,
  CountryCodes_044,
  CountryCodes_045,
  CountryCodes_046,
  CountryCodes_047,
  CountryCodes_048,
  CountryCodes_049,
  CountryCodes_050,
  CountryCodes_051,
  CountryCodes_052,
  CountryCodes_053,
  CountryCodes_054,
  CountryCodes_055,
  CountryCodes_056,
  CountryCodes_057,
  CountryCodes_058,
  CountryCodes_059,
  CountryCodes_060,
  CountryCodes_061,
  CountryCodes_062,
  CountryCodes_063,
  CountryCodes_064,
  CountryCodes_065,
  CountryCodes_066,
  CountryCodes_067,
  CountryCodes_068,
  CountryCodes_069,
  CountryCodes_070,
  CountryCodes_071,
  CountryCodes_072,
  CountryCodes_073,
  CountryCodes_074,
  CountryCodes_075,
  CountryCodes_076,
  CountryCodes_077,
  CountryCodes_078,
  CountryCodes_079,
  CountryCodes_080,
  CountryCodes_081,
  CountryCodes_082,
  CountryCodes_083,
  CountryCodes_084,
  CountryCodes_085,
  CountryCodes_086,
  CountryCodes_087,
  CountryCodes_088,
  CountryCodes_089,
  CountryCodes_090,
  CountryCodes_091,
  CountryCodes_092,
  CountryCodes_093,
  CountryCodes_094,
  CountryCodes_095,
  CountryCodes_096,
  CountryCodes_097,
  CountryCodes_098,
  CountryCodes_099,
  CountryCodes_100,
  CountryCodes_101,
  CountryCodes_102,
  CountryCodes_103,
  CountryCodes_104,
  CountryCodes_105,
  CountryCodes_106,
  CountryCodes_107,
  CountryCodes_108,
  CountryCodes_109,
  CountryCodes_110,
  CountryCodes_111,
  CountryCodes_112,
  CountryCodes_113,
  CountryCodes_114,
  CountryCodes_115,
  CountryCodes_116,
  CountryCodes_117,
  CountryCodes_118,
  CountryCodes_119,
  CountryCodes_120,
  CountryCodes_121,
  CountryCodes_122,
  CountryCodes_123,
  CountryCodes_124,
  CountryCodes_125,
  CountryCodes_126,
  CountryCodes_127,
  CountryCodes_128,
  CountryCodes_129,
  CountryCodes_130,
  CountryCodes_131,
  CountryCodes_132,
  CountryCodes_133,
  CountryCodes_134,
  CountryCodes_135,
  CountryCodes_136,
  CountryCodes_137,
  CountryCodes_138,
  CountryCodes_139,
  CountryCodes_140,
  CountryCodes_141,
  CountryCodes_142,
  CountryCodes_143,
  CountryCodes_144,
  CountryCodes_145,
  CountryCodes_146,
  CountryCodes_147,
  CountryCodes_148,
  CountryCodes_149,
  CountryCodes_150,
  CountryCodes_151,
  CountryCodes_152,
  CountryCodes_153,
  CountryCodes_154,
  CountryCodes_155,
  CountryCodes_156,
  CountryCodes_157,
  CountryCodes_158,
  CountryCodes_159,
  CountryCodes_160,
  CountryCodes_161,
  CountryCodes_162,
  CountryCodes_163,
  CountryCodes_164,
  CountryCodes_165,
  CountryCodes_166,
  CountryCodes_167,
  CountryCodes_168,
  CountryCodes_169,
  CountryCodes_170,
  CountryCodes_171,
  CountryCodes_172,
  CountryCodes_173,
  CountryCodes_174,
  CountryCodes_175,
  CountryCodes_176,
  CountryCodes_177,
  CountryCodes_178,
  CountryCodes_179,
  CountryCodes_180,
  CountryCodes_181,
  CountryCodes_182,
  CountryCodes_183,
  CountryCodes_184,
  CountryCodes_185,
  CountryCodes_186,
  CountryCodes_187,
  CountryCodes_188,
  CountryCodes_189,
  CountryCodes_190,
  CountryCodes_191,
  CountryCodes_192,
  CountryCodes_193,
  CountryCodes_194,
  CountryCodes_195,
  CountryCodes_196,
  CountryCodes_197,
  CountryCodes_198,
  CountryCodes_199,
  CountryCodes_200,
  CountryCodes_201,
  CountryCodes_202,
  CountryCodes_203,
  CountryCodes_204,
  CountryCodes_205,
  CountryCodes_206,
  CountryCodes_207,
  CountryCodes_208,
  CountryCodes_209,
  CountryCodes_210,
  CountryCodes_211,
  CountryCodes_212,
  CountryCodes_213,
  CountryCodes_214,
  CountryCodes_215,
  CountryCodes_216,
  CountryCodes_217,
  CountryCodes_218,
  CountryCodes_219,
  CountryCodes_220,
  CountryCodes_221,
  CountryCodes_222,
  CountryCodes_223,
  CountryCodes_224,
  CountryCodes_225,
  CountryCodes_226,
  CountryCodes_227,
  CountryCodes_228,
  CountryCodes_229,
  CountryCodes_230,
  CountryCodes_231,
  CountryCodes_232,
  CountryCodes_233,
  CountryCodes_234,
  CountryCodes_235,
  CountryCodes_236,
  CountryCodes_237,
  CountryCodes_238,
  CountryCodes_239,
  CountryCodes_240,
  CountryCodes_241,
  CountryCodes_242,
  CountryCodes_243,
  CountryCodes_244,
  CountryCodes_245,
  CountryCodes_246,
  CountryCodes_247
];

exports.CountryCodes = CountryCodes;
/* No side effect */
