// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function validateCountryCode(countryCode) {
  if (countryCode !== undefined) {
    return countryCode;
  }
  
}

function makePhoneNumber(countryCode, areaCode, prefix, lineNumber, extension) {
  if (countryCode !== undefined) {
    return /* record */[
            /* countryCode */countryCode,
            /* areaCode */areaCode,
            /* prefix */prefix,
            /* lineNumber */lineNumber,
            /* extension */extension
          ];
  } else {
    throw [
          Caml_builtin_exceptions.invalid_argument,
          "Invalid Country Code"
        ];
  }
}

var PhoneNumber = /* module */[
  /* CC */0,
  /* validateCountryCode */validateCountryCode,
  /* makePhoneNumber */makePhoneNumber
];

exports.PhoneNumber = PhoneNumber;
/* No side effect */
