// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function Default(T) {
  var show = function (prim) {
    return String(prim);
  };
  return /* module */[/* show */show];
}

function Custom(T) {
  var show = T[/* show */0];
  return /* module */[/* show */show];
}

var SHOW = /* module */[
  /* Default */Default,
  /* Custom */Custom
];

exports.SHOW = SHOW;
/* No side effect */
