// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Hashtbl = require("bs-platform/lib/js/hashtbl.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function Comp($star) {
  return /* module */[];
}

var Impl = /* module */[/* Comp */Comp];

var Props = /* module */[];

function equal(a, b) {
  var match = Caml_obj.caml_equal(a, b);
  if (match) {
    return true;
  } else {
    return false;
  }
}

var Cache = Hashtbl.Make(/* module */[
      /* equal */equal,
      /* hash */Hashtbl.hash
    ]);

function render(props) {
  var count = props[/* columnCount */0];
  var headerChildren = Caml_array.caml_make_vect(count, /* Node */Block.__(0, [
          /* Div */25,
          /* Nil */0,
          /* Nil */0
        ]));
  return /* Node */Block.__(0, [
            /* Div */25,
            /* Nil */0,
            /* Children */[headerChildren]
          ]);
}

var Header = /* module */[
  /* Props */Props,
  /* Cache */Cache,
  /* render */render
];

var myVdom_001 = /* Attrs */[/* array */[/* Style */Block.__(123, ["color: green"])]];

var myVdom_002 = /* Children */[/* array */[
    /* Node */Block.__(0, [
        /* Div */25,
        /* Nil */0,
        /* Nil */0
      ]),
    render(/* record */[/* columnCount */5])
  ]];

var myVdom = /* Node */Block.__(0, [
    /* Div */25,
    myVdom_001,
    myVdom_002
  ]);

exports.Impl = Impl;
exports.Comp = Comp;
exports.Header = Header;
exports.myVdom = myVdom;
/* Cache Not a pure module */
